version: '1'
services:
  anvil:
    image: ghcr.io/foundry-rs/foundry
    container_name: anvil
    environment:
      ANVIL_IP_ADDR: "127.0.0.1"
    working_dir: /anvil
    ports:
      - "8545:8545"
    command: anvil
  frontend:
    build: ../
    ports:
      - "2333:2333"